pipeline{
  agent any
  stages{
     stage("Maven Build"){
       steps{
            sh "mvn clean package"
            sh "mv target/*.war target/myweb.war"
             }
            }
     stage("Deploy"){
       steps{
          sshagent(['tomcat-server']) {
          sh """
          scp -o StrictHostKeyChecking=no target/myweb.war ubuntu@3.74.43.98:/opt/tomcat/webapps/
          ssh ubuntu@3.74.43.98 /opt/tomcat/bin/shutdown.sh
          ssh ubuntu@3.74.43.98 /opt/tomcat/bin/startup.sh
           """
            }
          }
        }
      }
    }