pipeline{
  agent {
        docker {
            image 'maven:3-alpine'
            args '-u root -v /tmp:/tmp -v $HOME/.m2:/root/.m2'
            reuseNode true
  stages{
    stage("Git Checkout"){
      steps{
            git credentialsId: 'github', url: 'https://github.com/edmitrenko/jenkins-java-app.git'
           }
          }
     stage("Maven Build"){
       steps{
            sh "mvn clean package"
            sh "mv target/*.war target/myweb.war"
             }
            }
     stage("Deploy"){
       steps{
          sshagent(['tomcat-server']) {
          sh """
          scp -o StrictHostKeyChecking=no target/myweb.war ubuntu@3.74.43.98:/opt/tomcat/webapps/
          ssh ubuntu@3.74.43.98 /opt/tomcat/bin/shutdown.sh
          ssh ubuntu@3.74.43.98 /opt/tomcat/bin/startup.sh
           """
            }
          }
        }
      }
    }