pipeline{
  agent any
  stages{
     stage("Maven Build"){
       steps{
            sh "mvn clean package"
            sh "mv target/*.war target/myweb.war"
             }
            }
     stage("Deploy"){
       steps{
          sshagent(['tomcat-server']) {
          sh """
          scp -o StrictHostKeyChecking=no target/myweb.war ubuntu@54.93.59.32:/opt/tomcat/webapps/
          ssh ubuntu@54.93.59.32 /opt/tomcat/bin/shutdown.sh
          ssh ubuntu@54.93.59.32 /opt/tomcat/bin/startup.sh
           """
            }
          }
        }
      }
    }